### ISSUE TITLE
github上拉下来的各模块无法打出压缩包

### ISSUE THREAD

**Issue by zhmxby** [vipshop/ncform#1]
github上拉去下来的各模块无法打出压缩包（min包）

原因是 **conf/webpack.config.js** 中
![image](https://user-images.githubusercontent.com/14817815/42882309-5a8aad28-8acb-11e8-8eeb-1b7f5d04f03c.png)

环境变量未配置

在 **conf/webpack.config.prd.js** 中加入DefinePlugin插件
```
new webpack.DefinePlugin({
   'process.env': {
      NODE_ENV: '"production"'
    }
})
```

**Comment by daniel-dx** [comment]
你只需要NODE_ENV=production npm run build就行了

**Comment by zhmxby** [comment]
好的，谢谢~
