### ISSUE TITLE
是否可以做到关联表单项的数据获取逻辑

### ISSUE THREAD

**Issue by Colstuwjx** [vipshop/ncform#12]
如题，需求是有三个select A 和 B、C，A选择了条目之后，会影响到B的choices，而A和B的choice，共同影响了C的choice，而这三块的数据获取都是相对独立的，请问这种情况该怎么处理？或者有什么好的改进思路吗？

谢谢。

**Comment by Colstuwjx** [comment]
Ping @daniel-dx

**Comment by daniel-dx** [comment]
请查看[Playground](https://vipshop.github.io/ncform/ncform-show/playground/index.html)中的这个例子哈

![image](https://user-images.githubusercontent.com/22042268/44696032-65908d80-aaa8-11e8-827b-1fa4a2529351.png)
