### ISSUE TITLE
请问如何设置checkbox限制可以被勾选的项目的数量

### ISSUE THREAD

**Issue by herowzz** [vipshop/ncform#21]
element-ui可以通过设置min和max可以限制被勾选的数量，请问在ncform中如何配置？

`<template>
  <el-checkbox-group 
    v-model="checkedCities1"
    :min="1"
    :max="2">
    <el-checkbox v-for="city in cities" :label="city" :key="city">{{city}}</el-checkbox>
  </el-checkbox-group>
</template>`

[参看文档](http://element-cn.eleme.io/#/zh-CN/component/checkbox#ke-xuan-xiang-mu-shu-liang-de-xian-zhi)

**Comment by daniel-dx** [comment]
你好，标准组件的checkbox暂不支持该配置，你可根据自己的需求实现自己的form control，具体请参考[EXT-DOC.md](https://github.com/vipshop/ncform/blob/master/EXT-DOC.md)

**Comment by daniel-dx** [comment]
当然，这边会考虑把这个特性加进标准组件里面

**Comment by daniel-dx** [comment]
最少跟最多的限制应该属于校验规则范畴，所以这边不考虑把这个特性加入checkbox标准组件的配置中，如想实现你所说的需求，可参考以下配置：

打开[ncform playground](https://vipshop.github.io/ncform/ncform-show/playground/index.html)，把以下配置粘贴进去
```
{
  "type": "object",
  "properties": {
    "colors": {
      "type": "array",
      "ui": {
        "widget": "checkbox",
        "widgetConfig": {
          "enumSource": [
            {
              "value": 1,
              "label": "red"
            },
            {
              "value": 2,
              "label": "green"
            },
            {
              "value": 3,
              "label": "blue"
            },
            {
              "value": 4,
              "label": "orange"
            }
          ]
        }
      },
      "rules": {
        "required": true,
        "minItems": {
          "value": 2,
          "errMsg": "最少选择2项"
        },
        "maxItems": {
          "value": 3,
          "errMsg": "最多选择3项"
        }
      }
    }
  }
}
```
