### ISSUE TITLE
`ui.linkFields`字段如何绑定与`customRule`

### ISSUE THREAD

**Issue by cky917** [vipshop/ncform#22]
当一个字段自身不需要校验，但是它的改变需要触发别的字段的`customRule`时，如何绑定呢？

**Comment by daniel-dx** [comment]
你好，建议用[linkFields](https://github.com/vipshop/ncform/blob/master/CONFIG.md)

**Comment by cky917** [comment]
@daniel-dx 感谢回复，但是我看文档`linkFields`里只能绑定带有名字的`rules`,  对于`customRule`怎么绑定呢? 用`customRuleIdx`? 我试了一下没用。。

**Comment by daniel-dx** [comment]
目前建议增加自定义的rule类型来实现需求，然后配合`linkFields`来使用（`customRule`的设计目前有点问题，后面可能会作修改）
